# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# Define the Flutter root path
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

# Include the Flutter pod helper
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

# Setup for Flutter iOS Podfile
flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  # Install all Flutter iOS pods
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))

  # Unit tests for the project
  target 'RunnerTests' do
    inherit! :search_paths
    # Add any additional testing dependencies here
  end
end

# Post-install configuration
post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Ensures additional build settings are applied
    flutter_additional_ios_build_settings(target)

    # Fix for Xcode 12 and above when using `use_frameworks!`
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
    end
  end
end
